---
- name: Testing andrewrothstein.kubeseal
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kubeseal --version'
      ansible.builtin.command: /usr/local/bin/kubeseal --version
      changed_when: false
      register: kubeseal_test_output
    - name: Output from 'kubeseal --version'
      ansible.builtin.debug:
        msg: '{{ kubeseal_test_output.stdout }}'
