---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: checking for install in {{ kubeseal_install_exe }}
  become: '{{ kubeseal_escalate }}'
  stat:
    path: '{{ kubeseal_install_dir }}'
  changed_when: false
  register: kubeseal_binary
- when: not kubeseal_binary.stat.exists
  block:
    - name: downloading {{ kubeseal_url }} to {{ kubeseal_tmp_archive }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      get_url:
        url: '{{ kubeseal_url }}'
        dest: '{{ kubeseal_tmp_archive }}'
        checksum: '{{ kubeseal_checksum }}'
        mode: 0644
    - name: mkdir {{ kubeseal_install_dir }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      file:
        path: '{{ kubeseal_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ kubeseal_tmp_archive }} to {{ kubeseal_install_dir }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ kubeseal_tmp_archive }}'
        dest: '{{ kubeseal_install_dir }}'
        creates: '{{ kubeseal_install_exe }}'
  always:
    - name: rm {{ kubeseal_tmp_archive }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      file:
        path: '{{ kubeseal_tmp_archive }}'
        state: absent
- name: linking {{ kubeseal_link }} to {{ kubeseal_install_exe }}
  become: '{{ kubeseal_escalate }}'
  become_user: root
  file:
    src: '{{ kubeseal_install_exe }}'
    dest: '{{ kubeseal_link }}'
    state: link
