---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Checking for install in {{ kubeseal_install_exe }}
  become: '{{ kubeseal_escalate }}'
  ansible.builtin.stat:
    path: '{{ kubeseal_install_dir }}'
  changed_when: false
  register: kubeseal_binary
- name: Downloading and installing kubeseal
  when: not kubeseal_binary.stat.exists
  block:
    - name: Downloading {{ kubeseal_url }} to {{ kubeseal_tmp_archive }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      ansible.builtin.get_url:
        url: '{{ kubeseal_url }}'
        dest: '{{ kubeseal_tmp_archive }}'
        checksum: '{{ kubeseal_checksum }}'
        mode: '644'
    - name: Mkdir {{ kubeseal_install_dir }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ kubeseal_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ kubeseal_tmp_archive }} to {{ kubeseal_install_dir }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ kubeseal_tmp_archive }}'
        dest: '{{ kubeseal_install_dir }}'
        creates: '{{ kubeseal_install_exe }}'
  always:
    - name: Rm {{ kubeseal_tmp_archive }}
      become: '{{ kubeseal_escalate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ kubeseal_tmp_archive }}'
        state: absent
- name: Linking {{ kubeseal_link }} to {{ kubeseal_install_exe }}
  become: '{{ kubeseal_escalate }}'
  become_user: root
  ansible.builtin.file:
    src: '{{ kubeseal_install_exe }}'
    dest: '{{ kubeseal_link }}'
    state: link
